# Build with the same lockfile the repo uses (pnpm), not npm.
FROM node:22-alpine AS build
WORKDIR /app
RUN corepack enable

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .
RUN pnpm run build

# Standalone output: .next/standalone already contains a minimal server +
# traced node_modules, so the runtime image stays small and runs unprivileged.
FROM node:22-alpine AS production
WORKDIR /app
ENV NODE_ENV=production

RUN addgroup --system --gid 1001 nextjs \
    && adduser --system --uid 1001 nextjs

COPY --from=build /app/.next/standalone ./
COPY --from=build /app/.next/static ./.next/static
COPY --from=build /app/public ./public
# Standalone output tracing skips src/, but RETRIEVER=embeddings reads
# src/data/embeddings.json at request time. The dir is committed; the JSON
# inside is optional (generated by `pnpm run embeddings`).
COPY --from=build /app/src/data/ ./src/data/

USER nextjs
EXPOSE 3000
CMD ["node", "server.js"]
